"""Add uploaded_at timestamp to complaint_images

Revision ID: 039e5d99cb6e
Revises: bfdb3e8321a2
Create Date: 2025-12-13 20:59:04.920917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039e5d99cb6e'
down_revision: Union[str, None] = 'bfdb3e8321a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('osm_id', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('has_lighting', sa.Boolean(), nullable=True),
    sa.Column('has_water', sa.Boolean(), nullable=True),
    sa.Column('has_toilet', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id')
    )
    op.create_index(op.f('ix_assembly_points_id'), 'assembly_points', ['id'], unique=False)
    op.add_column('complaint_images', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint_images', 'uploaded_at')
    op.drop_index(op.f('ix_assembly_points_id'), table_name='assembly_points')
    op.drop_table('assembly_points')
    # ### end Alembic commands ###

