"""Initial tables

Revision ID: 6fc732509539
Revises: 
Create Date: 2025-12-12 23:12:45.478045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc732509539'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('station_name', sa.String(length=255), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('GOOD', 'MODERATE', 'UNHEALTHY_SENSITIVE', 'UNHEALTHY', 'VERY_UNHEALTHY', 'HAZARDOUS', name='airqualitylevel'), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('o3', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_quality_readings_id'), 'air_quality_readings', ['id'], unique=False)
    op.create_index(op.f('ix_air_quality_readings_recorded_at'), 'air_quality_readings', ['recorded_at'], unique=False)
    op.create_table('blocked_roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_name', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('end_latitude', sa.Float(), nullable=False),
    sa.Column('end_longitude', sa.Float(), nullable=False),
    sa.Column('alternative_route', sa.Text(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.Column('unblocked_at', sa.DateTime(), nullable=True),
    sa.Column('disaster_mode_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_roads_id'), 'blocked_roads', ['id'], unique=False)
    op.create_table('disaster_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disaster_type', sa.Enum('EARTHQUAKE', 'FLOOD', 'FIRE', 'STORM', 'LANDSLIDE', 'OTHER', name='disastertype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='disasterseverity'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('center_latitude', sa.Float(), nullable=False),
    sa.Column('center_longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disaster_modes_id'), 'disaster_modes', ['id'], unique=False)
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('has_emergency', sa.Boolean(), nullable=True),
    sa.Column('speciality', sa.String(length=255), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_osm_id'), 'hospitals', ['osm_id'], unique=True)
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_on_duty', sa.Boolean(), nullable=True),
    sa.Column('duty_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_id'), 'pharmacies', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacies_osm_id'), 'pharmacies', ['osm_id'], unique=True)
    op.create_table('roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('road_type', sa.String(length=50), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=False),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('lanes', sa.Integer(), nullable=True),
    sa.Column('max_speed', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('blocked_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roads_id'), 'roads', ['id'], unique=False)
    op.create_index(op.f('ix_roads_osm_id'), 'roads', ['osm_id'], unique=False)
    op.create_table('safe_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=False),
    sa.Column('start_name', sa.String(length=255), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('end_name', sa.String(length=255), nullable=True),
    sa.Column('end_latitude', sa.Float(), nullable=False),
    sa.Column('end_longitude', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_walk_time_min', sa.Float(), nullable=True),
    sa.Column('capacity_people', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('disaster_mode_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safe_routes_id'), 'safe_routes', ['id'], unique=False)
    op.create_table('shadow_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=False),
    sa.Column('start_name', sa.String(length=255), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('end_name', sa.String(length=255), nullable=True),
    sa.Column('end_latitude', sa.Float(), nullable=False),
    sa.Column('end_longitude', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_walk_time_min', sa.Float(), nullable=True),
    sa.Column('shade_percentage', sa.Float(), nullable=True),
    sa.Column('is_shaded_route', sa.Boolean(), nullable=True),
    sa.Column('is_lit_route', sa.Boolean(), nullable=True),
    sa.Column('best_shade_start_time', sa.Time(), nullable=True),
    sa.Column('best_shade_end_time', sa.Time(), nullable=True),
    sa.Column('shade_sources', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_routes_id'), 'shadow_routes', ['id'], unique=False)
    op.create_table('traffic_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('road_name', sa.String(length=255), nullable=True),
    sa.Column('traffic_level', sa.Enum('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='trafficlevel'), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('congestion_percent', sa.Float(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_points_id'), 'traffic_points', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_points_recorded_at'), 'traffic_points', ['recorded_at'], unique=False)
    op.create_table('trash_bins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('bin_type', sa.Enum('GENERAL', 'RECYCLABLE', 'ORGANIC', 'GLASS', 'PAPER', 'PLASTIC', name='trashbintype'), nullable=True),
    sa.Column('capacity_liters', sa.Integer(), nullable=True),
    sa.Column('fill_level', sa.Float(), nullable=True),
    sa.Column('last_fill_update', sa.DateTime(), nullable=True),
    sa.Column('sensor_id', sa.String(length=100), nullable=True),
    sa.Column('has_sensor', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('needs_maintenance', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_id')
    )
    op.create_index(op.f('ix_trash_bins_id'), 'trash_bins', ['id'], unique=False)
    op.create_table('trash_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('waypoints', sa.Text(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration_min', sa.Float(), nullable=True),
    sa.Column('estimated_fuel_liters', sa.Float(), nullable=True),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('vehicle_capacity_kg', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_optimized', sa.Boolean(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trash_routes_id'), 'trash_routes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'MUNICIPALITY', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ROAD_DAMAGE', 'LIGHTING', 'TRASH', 'TRAFFIC', 'PARKING', 'NOISE', 'GREEN_AREA', 'WATER', 'AIR_QUALITY', 'SAFETY', 'OTHER', name='complaintcategory'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='complaintstatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='complaintpriority'), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('ai_verified', sa.Boolean(), nullable=True),
    sa.Column('ai_verification_score', sa.Float(), nullable=True),
    sa.Column('ai_category_suggestion', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_table('trash_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trash_bin_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('fill_level_before', sa.Float(), nullable=True),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['trash_routes.id'], ),
    sa.ForeignKeyConstraint(['trash_bin_id'], ['trash_bins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trash_collections_id'), 'trash_collections', ['id'], unique=False)
    op.create_table('complaint_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('municipality_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('new_status', sa.Enum('PENDING', 'RECEIVED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='complaintstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['municipality_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_feedbacks_id'), 'complaint_feedbacks', ['id'], unique=False)
    op.create_table('complaint_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('ai_tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_images_id'), 'complaint_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_images_id'), table_name='complaint_images')
    op.drop_table('complaint_images')
    op.drop_index(op.f('ix_complaint_feedbacks_id'), table_name='complaint_feedbacks')
    op.drop_table('complaint_feedbacks')
    op.drop_index(op.f('ix_trash_collections_id'), table_name='trash_collections')
    op.drop_table('trash_collections')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trash_routes_id'), table_name='trash_routes')
    op.drop_table('trash_routes')
    op.drop_index(op.f('ix_trash_bins_id'), table_name='trash_bins')
    op.drop_table('trash_bins')
    op.drop_index(op.f('ix_traffic_points_recorded_at'), table_name='traffic_points')
    op.drop_index(op.f('ix_traffic_points_id'), table_name='traffic_points')
    op.drop_table('traffic_points')
    op.drop_index(op.f('ix_shadow_routes_id'), table_name='shadow_routes')
    op.drop_table('shadow_routes')
    op.drop_index(op.f('ix_safe_routes_id'), table_name='safe_routes')
    op.drop_table('safe_routes')
    op.drop_index(op.f('ix_roads_osm_id'), table_name='roads')
    op.drop_index(op.f('ix_roads_id'), table_name='roads')
    op.drop_table('roads')
    op.drop_index(op.f('ix_pharmacies_osm_id'), table_name='pharmacies')
    op.drop_index(op.f('ix_pharmacies_id'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index(op.f('ix_hospitals_osm_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_disaster_modes_id'), table_name='disaster_modes')
    op.drop_table('disaster_modes')
    op.drop_index(op.f('ix_blocked_roads_id'), table_name='blocked_roads')
    op.drop_table('blocked_roads')
    op.drop_index(op.f('ix_air_quality_readings_recorded_at'), table_name='air_quality_readings')
    op.drop_index(op.f('ix_air_quality_readings_id'), table_name='air_quality_readings')
    op.drop_table('air_quality_readings')
    # ### end Alembic commands ###

