"""add_road_shadow_model

Revision ID: 722eb323493f
Revises: 1e17be66a8f3
Create Date: 2025-12-14 06:45:18.010386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '722eb323493f'
down_revision: Union[str, None] = '1e17be66a8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_shadows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.String(length=50), nullable=True),
    sa.Column('road_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('shade_score', sa.Float(), nullable=False),
    sa.Column('shade_percentage', sa.Float(), nullable=True),
    sa.Column('shade_mean', sa.Float(), nullable=True),
    sa.Column('shade_max', sa.Float(), nullable=True),
    sa.Column('shade_min', sa.Float(), nullable=True),
    sa.Column('geometry', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_road_shadow_location', 'road_shadows', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_road_shadows_id'), 'road_shadows', ['id'], unique=False)
    op.create_index(op.f('ix_road_shadows_road_id'), 'road_shadows', ['road_id'], unique=False)
    op.create_index(op.f('ix_road_shadows_segment_id'), 'road_shadows', ['segment_id'], unique=False)
    # Not: trash, disaster ve assembly point tabloları zaten kaldırılmış olabilir
    # Bu migration sadece road_shadows tablosunu oluşturur
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Sadece road_shadows tablosunu kaldır
    op.drop_index(op.f('ix_road_shadows_segment_id'), table_name='road_shadows')
    op.drop_index(op.f('ix_road_shadows_road_id'), table_name='road_shadows')
    op.drop_index(op.f('ix_road_shadows_id'), table_name='road_shadows')
    op.drop_index('idx_road_shadow_location', table_name='road_shadows')
    op.drop_table('road_shadows')
    # ### end Alembic commands ###
