"""Add segment lighting table

Revision ID: a1b2c3d4e5f6
Revises: 71a0744a1c41
Create Date: 2025-01-14 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '71a0744a1c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum zaten varsa oluşturma (checkfirst=True ile)
    from sqlalchemy.dialects import postgresql
    enum_type = postgresql.ENUM('DARK', 'MEDIUM', 'BRIGHT', name='lightinglevel', create_type=False)
    enum_type.create(op.get_bind(), checkfirst=True)
    
    op.create_table(
        'segment_lighting',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('segment_id', sa.String(length=50), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('lighting_score', sa.Float(), nullable=False),
        sa.Column('lighting_level', postgresql.ENUM('DARK', 'MEDIUM', 'BRIGHT', name='lightinglevel', create_type=False), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_lighting_segment_id'), 'segment_lighting', ['segment_id'], unique=False)
    op.create_index(op.f('ix_segment_lighting_id'), 'segment_lighting', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_lighting_id'), table_name='segment_lighting')
    op.drop_index(op.f('ix_segment_lighting_segment_id'), table_name='segment_lighting')
    op.drop_table('segment_lighting')
    # ### end Alembic commands ###

